sudo: false

language: node_js

addons:
  firefox: "17.0"

node_js:
  - 'node'
  - 8

before_script:
  - tar -xf repo1.tar
  - npm install selenium-standalone -g
  - selenium-standalone install

script:
  - npm run lint
  - npm run unit-test
  - node server.js &
  - selenium-standalone start &
  - npm run integration-test
