sudo: false

language: node_js

node_js:
  - 'node'
  - 8

script:
  - tar -xf repo1.tar
  - npm run lint
  - npm run unit-test
  - npm install selenium-standalone -g
  - selenium-standalone install
  - npm run start
  - npm run integration-test